//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 11.0.50727.1
// 
namespace Libreria.svcLibreria {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="svcLibreria.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerListaTodosLibros", ReplyAction="http://tempuri.org/IService1/ObtenerListaTodosLibrosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Libreria.svcLibreria.ObtenerListaTodosLibrosResponse> ObtenerListaTodosLibrosAsync(Libreria.svcLibreria.ObtenerListaTodosLibrosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerListaAutores", ReplyAction="http://tempuri.org/IService1/ObtenerListaAutoresResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Libreria.svcLibreria.ObtenerListaAutoresResponse> ObtenerListaAutoresAsync(Libreria.svcLibreria.ObtenerListaAutoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerListaTodosGeneros", ReplyAction="http://tempuri.org/IService1/ObtenerListaTodosGenerosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Libreria.svcLibreria.ObtenerListaTodosGenerosResponse> ObtenerListaTodosGenerosAsync(Libreria.svcLibreria.ObtenerListaTodosGenerosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerListaEditoriales", ReplyAction="http://tempuri.org/IService1/ObtenerListaEditorialesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Libreria.svcLibreria.ObtenerListaEditorialesResponse> ObtenerListaEditorialesAsync(Libreria.svcLibreria.ObtenerListaEditorialesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerListaLibrosXAutor", ReplyAction="http://tempuri.org/IService1/ObtenerListaLibrosXAutorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Libreria.svcLibreria.ObtenerListaLibrosXAutorResponse> ObtenerListaLibrosXAutorAsync(Libreria.svcLibreria.ObtenerListaLibrosXAutorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerListaLibrosXGenero", ReplyAction="http://tempuri.org/IService1/ObtenerListaLibrosXGeneroResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Libreria.svcLibreria.ObtenerListaLibrosXGeneroResponse> ObtenerListaLibrosXGeneroAsync(Libreria.svcLibreria.ObtenerListaLibrosXGeneroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerListaLibrosXEditorial", ReplyAction="http://tempuri.org/IService1/ObtenerListaLibrosXEditorialResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Libreria.svcLibreria.ObtenerListaLibrosXEditorialResponse> ObtenerListaLibrosXEditorialAsync(Libreria.svcLibreria.ObtenerListaLibrosXEditorialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NuevoLibro", ReplyAction="http://tempuri.org/IService1/NuevoLibroResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Libreria.svcLibreria.NuevoLibroResponse> NuevoLibroAsync(Libreria.svcLibreria.NuevoLibroRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/examen2")]
    public partial class Libro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int autorIDField;
        
        private bool autorIDFieldSpecified;
        
        private string descripcionField;
        
        private int editorialIDField;
        
        private bool editorialIDFieldSpecified;
        
        private int generoIDField;
        
        private bool generoIDFieldSpecified;
        
        private string idiomaField;
        
        private string imagenURLField;
        
        private int libroIDField;
        
        private bool libroIDFieldSpecified;
        
        private int noPaginasField;
        
        private bool noPaginasFieldSpecified;
        
        private string nombreField;
        
        private string paisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int AutorID {
            get {
                return this.autorIDField;
            }
            set {
                this.autorIDField = value;
                this.RaisePropertyChanged("AutorID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AutorIDSpecified {
            get {
                return this.autorIDFieldSpecified;
            }
            set {
                this.autorIDFieldSpecified = value;
                this.RaisePropertyChanged("AutorIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int EditorialID {
            get {
                return this.editorialIDField;
            }
            set {
                this.editorialIDField = value;
                this.RaisePropertyChanged("EditorialID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EditorialIDSpecified {
            get {
                return this.editorialIDFieldSpecified;
            }
            set {
                this.editorialIDFieldSpecified = value;
                this.RaisePropertyChanged("EditorialIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int GeneroID {
            get {
                return this.generoIDField;
            }
            set {
                this.generoIDField = value;
                this.RaisePropertyChanged("GeneroID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GeneroIDSpecified {
            get {
                return this.generoIDFieldSpecified;
            }
            set {
                this.generoIDFieldSpecified = value;
                this.RaisePropertyChanged("GeneroIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string Idioma {
            get {
                return this.idiomaField;
            }
            set {
                this.idiomaField = value;
                this.RaisePropertyChanged("Idioma");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string ImagenURL {
            get {
                return this.imagenURLField;
            }
            set {
                this.imagenURLField = value;
                this.RaisePropertyChanged("ImagenURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int LibroID {
            get {
                return this.libroIDField;
            }
            set {
                this.libroIDField = value;
                this.RaisePropertyChanged("LibroID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LibroIDSpecified {
            get {
                return this.libroIDFieldSpecified;
            }
            set {
                this.libroIDFieldSpecified = value;
                this.RaisePropertyChanged("LibroIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int NoPaginas {
            get {
                return this.noPaginasField;
            }
            set {
                this.noPaginasField = value;
                this.RaisePropertyChanged("NoPaginas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NoPaginasSpecified {
            get {
                return this.noPaginasFieldSpecified;
            }
            set {
                this.noPaginasFieldSpecified = value;
                this.RaisePropertyChanged("NoPaginasSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string Pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
                this.RaisePropertyChanged("Pais");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/examen2")]
    public partial class Editorial : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string direccionField;
        
        private int editorialIDField;
        
        private bool editorialIDFieldSpecified;
        
        private string estadoField;
        
        private string imagenURLField;
        
        private Libro[] listaLibrosField;
        
        private string nombreField;
        
        private string paisField;
        
        private string uRLEditorialField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("Direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int EditorialID {
            get {
                return this.editorialIDField;
            }
            set {
                this.editorialIDField = value;
                this.RaisePropertyChanged("EditorialID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EditorialIDSpecified {
            get {
                return this.editorialIDFieldSpecified;
            }
            set {
                this.editorialIDFieldSpecified = value;
                this.RaisePropertyChanged("EditorialIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string ImagenURL {
            get {
                return this.imagenURLField;
            }
            set {
                this.imagenURLField = value;
                this.RaisePropertyChanged("ImagenURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=4)]
        public Libro[] ListaLibros {
            get {
                return this.listaLibrosField;
            }
            set {
                this.listaLibrosField = value;
                this.RaisePropertyChanged("ListaLibros");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string Pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
                this.RaisePropertyChanged("Pais");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string URLEditorial {
            get {
                return this.uRLEditorialField;
            }
            set {
                this.uRLEditorialField = value;
                this.RaisePropertyChanged("URLEditorial");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/examen2")]
    public partial class Genero : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int generoIDField;
        
        private bool generoIDFieldSpecified;
        
        private string imagenURLField;
        
        private Libro[] listaLibrosField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int GeneroID {
            get {
                return this.generoIDField;
            }
            set {
                this.generoIDField = value;
                this.RaisePropertyChanged("GeneroID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GeneroIDSpecified {
            get {
                return this.generoIDFieldSpecified;
            }
            set {
                this.generoIDFieldSpecified = value;
                this.RaisePropertyChanged("GeneroIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string ImagenURL {
            get {
                return this.imagenURLField;
            }
            set {
                this.imagenURLField = value;
                this.RaisePropertyChanged("ImagenURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        public Libro[] ListaLibros {
            get {
                return this.listaLibrosField;
            }
            set {
                this.listaLibrosField = value;
                this.RaisePropertyChanged("ListaLibros");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/examen2")]
    public partial class Autor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apPaternoField;
        
        private int autorIDField;
        
        private bool autorIDFieldSpecified;
        
        private Libro[] listaLibrosField;
        
        private string nacionalidadField;
        
        private string nombreField;
        
        private string urlImgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string ApPaterno {
            get {
                return this.apPaternoField;
            }
            set {
                this.apPaternoField = value;
                this.RaisePropertyChanged("ApPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int AutorID {
            get {
                return this.autorIDField;
            }
            set {
                this.autorIDField = value;
                this.RaisePropertyChanged("AutorID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AutorIDSpecified {
            get {
                return this.autorIDFieldSpecified;
            }
            set {
                this.autorIDFieldSpecified = value;
                this.RaisePropertyChanged("AutorIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        public Libro[] ListaLibros {
            get {
                return this.listaLibrosField;
            }
            set {
                this.listaLibrosField = value;
                this.RaisePropertyChanged("ListaLibros");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Nacionalidad {
            get {
                return this.nacionalidadField;
            }
            set {
                this.nacionalidadField = value;
                this.RaisePropertyChanged("Nacionalidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string UrlImg {
            get {
                return this.urlImgField;
            }
            set {
                this.urlImgField = value;
                this.RaisePropertyChanged("UrlImg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerListaTodosLibros", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerListaTodosLibrosRequest {
        
        public ObtenerListaTodosLibrosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerListaTodosLibrosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerListaTodosLibrosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/examen2")]
        public Libreria.svcLibreria.Libro[] ObtenerListaTodosLibrosResult;
        
        public ObtenerListaTodosLibrosResponse() {
        }
        
        public ObtenerListaTodosLibrosResponse(Libreria.svcLibreria.Libro[] ObtenerListaTodosLibrosResult) {
            this.ObtenerListaTodosLibrosResult = ObtenerListaTodosLibrosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerListaAutores", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerListaAutoresRequest {
        
        public ObtenerListaAutoresRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerListaAutoresResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerListaAutoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/examen2")]
        public Libreria.svcLibreria.Autor[] ObtenerListaAutoresResult;
        
        public ObtenerListaAutoresResponse() {
        }
        
        public ObtenerListaAutoresResponse(Libreria.svcLibreria.Autor[] ObtenerListaAutoresResult) {
            this.ObtenerListaAutoresResult = ObtenerListaAutoresResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerListaTodosGeneros", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerListaTodosGenerosRequest {
        
        public ObtenerListaTodosGenerosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerListaTodosGenerosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerListaTodosGenerosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/examen2")]
        public Libreria.svcLibreria.Genero[] ObtenerListaTodosGenerosResult;
        
        public ObtenerListaTodosGenerosResponse() {
        }
        
        public ObtenerListaTodosGenerosResponse(Libreria.svcLibreria.Genero[] ObtenerListaTodosGenerosResult) {
            this.ObtenerListaTodosGenerosResult = ObtenerListaTodosGenerosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerListaEditoriales", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerListaEditorialesRequest {
        
        public ObtenerListaEditorialesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerListaEditorialesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerListaEditorialesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/examen2")]
        public Libreria.svcLibreria.Editorial[] ObtenerListaEditorialesResult;
        
        public ObtenerListaEditorialesResponse() {
        }
        
        public ObtenerListaEditorialesResponse(Libreria.svcLibreria.Editorial[] ObtenerListaEditorialesResult) {
            this.ObtenerListaEditorialesResult = ObtenerListaEditorialesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerListaLibrosXAutor", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerListaLibrosXAutorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int AutorID;
        
        public ObtenerListaLibrosXAutorRequest() {
        }
        
        public ObtenerListaLibrosXAutorRequest(int AutorID) {
            this.AutorID = AutorID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerListaLibrosXAutorResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerListaLibrosXAutorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Libreria.svcLibreria.ArrayOfXElement ObtenerListaLibrosXAutorResult;
        
        public ObtenerListaLibrosXAutorResponse() {
        }
        
        public ObtenerListaLibrosXAutorResponse(Libreria.svcLibreria.ArrayOfXElement ObtenerListaLibrosXAutorResult) {
            this.ObtenerListaLibrosXAutorResult = ObtenerListaLibrosXAutorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerListaLibrosXGenero", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerListaLibrosXGeneroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int GeneroID;
        
        public ObtenerListaLibrosXGeneroRequest() {
        }
        
        public ObtenerListaLibrosXGeneroRequest(int GeneroID) {
            this.GeneroID = GeneroID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerListaLibrosXGeneroResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerListaLibrosXGeneroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Libreria.svcLibreria.ArrayOfXElement ObtenerListaLibrosXGeneroResult;
        
        public ObtenerListaLibrosXGeneroResponse() {
        }
        
        public ObtenerListaLibrosXGeneroResponse(Libreria.svcLibreria.ArrayOfXElement ObtenerListaLibrosXGeneroResult) {
            this.ObtenerListaLibrosXGeneroResult = ObtenerListaLibrosXGeneroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerListaLibrosXEditorial", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerListaLibrosXEditorialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int EditorialID;
        
        public ObtenerListaLibrosXEditorialRequest() {
        }
        
        public ObtenerListaLibrosXEditorialRequest(int EditorialID) {
            this.EditorialID = EditorialID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerListaLibrosXEditorialResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerListaLibrosXEditorialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Libreria.svcLibreria.ArrayOfXElement ObtenerListaLibrosXEditorialResult;
        
        public ObtenerListaLibrosXEditorialResponse() {
        }
        
        public ObtenerListaLibrosXEditorialResponse(Libreria.svcLibreria.ArrayOfXElement ObtenerListaLibrosXEditorialResult) {
            this.ObtenerListaLibrosXEditorialResult = ObtenerListaLibrosXEditorialResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NuevoLibro", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class NuevoLibroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int autor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int editorial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int genero;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string idioma;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pais;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public int paginas;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ImagenURL;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Descripcion;
        
        public NuevoLibroRequest() {
        }
        
        public NuevoLibroRequest(string nombre, int autor, int editorial, int genero, string idioma, string pais, int paginas, string ImagenURL, string Descripcion) {
            this.nombre = nombre;
            this.autor = autor;
            this.editorial = editorial;
            this.genero = genero;
            this.idioma = idioma;
            this.pais = pais;
            this.paginas = paginas;
            this.ImagenURL = ImagenURL;
            this.Descripcion = Descripcion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NuevoLibroResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class NuevoLibroResponse {
        
        public NuevoLibroResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Libreria.svcLibreria.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Libreria.svcLibreria.IService1>, Libreria.svcLibreria.IService1 {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Libreria.svcLibreria.ObtenerListaTodosLibrosResponse> Libreria.svcLibreria.IService1.ObtenerListaTodosLibrosAsync(Libreria.svcLibreria.ObtenerListaTodosLibrosRequest request) {
            return base.Channel.ObtenerListaTodosLibrosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Libreria.svcLibreria.ObtenerListaTodosLibrosResponse> ObtenerListaTodosLibrosAsync() {
            Libreria.svcLibreria.ObtenerListaTodosLibrosRequest inValue = new Libreria.svcLibreria.ObtenerListaTodosLibrosRequest();
            return ((Libreria.svcLibreria.IService1)(this)).ObtenerListaTodosLibrosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Libreria.svcLibreria.ObtenerListaAutoresResponse> Libreria.svcLibreria.IService1.ObtenerListaAutoresAsync(Libreria.svcLibreria.ObtenerListaAutoresRequest request) {
            return base.Channel.ObtenerListaAutoresAsync(request);
        }
        
        public System.Threading.Tasks.Task<Libreria.svcLibreria.ObtenerListaAutoresResponse> ObtenerListaAutoresAsync() {
            Libreria.svcLibreria.ObtenerListaAutoresRequest inValue = new Libreria.svcLibreria.ObtenerListaAutoresRequest();
            return ((Libreria.svcLibreria.IService1)(this)).ObtenerListaAutoresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Libreria.svcLibreria.ObtenerListaTodosGenerosResponse> Libreria.svcLibreria.IService1.ObtenerListaTodosGenerosAsync(Libreria.svcLibreria.ObtenerListaTodosGenerosRequest request) {
            return base.Channel.ObtenerListaTodosGenerosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Libreria.svcLibreria.ObtenerListaTodosGenerosResponse> ObtenerListaTodosGenerosAsync() {
            Libreria.svcLibreria.ObtenerListaTodosGenerosRequest inValue = new Libreria.svcLibreria.ObtenerListaTodosGenerosRequest();
            return ((Libreria.svcLibreria.IService1)(this)).ObtenerListaTodosGenerosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Libreria.svcLibreria.ObtenerListaEditorialesResponse> Libreria.svcLibreria.IService1.ObtenerListaEditorialesAsync(Libreria.svcLibreria.ObtenerListaEditorialesRequest request) {
            return base.Channel.ObtenerListaEditorialesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Libreria.svcLibreria.ObtenerListaEditorialesResponse> ObtenerListaEditorialesAsync() {
            Libreria.svcLibreria.ObtenerListaEditorialesRequest inValue = new Libreria.svcLibreria.ObtenerListaEditorialesRequest();
            return ((Libreria.svcLibreria.IService1)(this)).ObtenerListaEditorialesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Libreria.svcLibreria.ObtenerListaLibrosXAutorResponse> Libreria.svcLibreria.IService1.ObtenerListaLibrosXAutorAsync(Libreria.svcLibreria.ObtenerListaLibrosXAutorRequest request) {
            return base.Channel.ObtenerListaLibrosXAutorAsync(request);
        }
        
        public System.Threading.Tasks.Task<Libreria.svcLibreria.ObtenerListaLibrosXAutorResponse> ObtenerListaLibrosXAutorAsync(int AutorID) {
            Libreria.svcLibreria.ObtenerListaLibrosXAutorRequest inValue = new Libreria.svcLibreria.ObtenerListaLibrosXAutorRequest();
            inValue.AutorID = AutorID;
            return ((Libreria.svcLibreria.IService1)(this)).ObtenerListaLibrosXAutorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Libreria.svcLibreria.ObtenerListaLibrosXGeneroResponse> Libreria.svcLibreria.IService1.ObtenerListaLibrosXGeneroAsync(Libreria.svcLibreria.ObtenerListaLibrosXGeneroRequest request) {
            return base.Channel.ObtenerListaLibrosXGeneroAsync(request);
        }
        
        public System.Threading.Tasks.Task<Libreria.svcLibreria.ObtenerListaLibrosXGeneroResponse> ObtenerListaLibrosXGeneroAsync(int GeneroID) {
            Libreria.svcLibreria.ObtenerListaLibrosXGeneroRequest inValue = new Libreria.svcLibreria.ObtenerListaLibrosXGeneroRequest();
            inValue.GeneroID = GeneroID;
            return ((Libreria.svcLibreria.IService1)(this)).ObtenerListaLibrosXGeneroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Libreria.svcLibreria.ObtenerListaLibrosXEditorialResponse> Libreria.svcLibreria.IService1.ObtenerListaLibrosXEditorialAsync(Libreria.svcLibreria.ObtenerListaLibrosXEditorialRequest request) {
            return base.Channel.ObtenerListaLibrosXEditorialAsync(request);
        }
        
        public System.Threading.Tasks.Task<Libreria.svcLibreria.ObtenerListaLibrosXEditorialResponse> ObtenerListaLibrosXEditorialAsync(int EditorialID) {
            Libreria.svcLibreria.ObtenerListaLibrosXEditorialRequest inValue = new Libreria.svcLibreria.ObtenerListaLibrosXEditorialRequest();
            inValue.EditorialID = EditorialID;
            return ((Libreria.svcLibreria.IService1)(this)).ObtenerListaLibrosXEditorialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Libreria.svcLibreria.NuevoLibroResponse> Libreria.svcLibreria.IService1.NuevoLibroAsync(Libreria.svcLibreria.NuevoLibroRequest request) {
            return base.Channel.NuevoLibroAsync(request);
        }
        
        public System.Threading.Tasks.Task<Libreria.svcLibreria.NuevoLibroResponse> NuevoLibroAsync(string nombre, int autor, int editorial, int genero, string idioma, string pais, int paginas, string ImagenURL, string Descripcion) {
            Libreria.svcLibreria.NuevoLibroRequest inValue = new Libreria.svcLibreria.NuevoLibroRequest();
            inValue.nombre = nombre;
            inValue.autor = autor;
            inValue.editorial = editorial;
            inValue.genero = genero;
            inValue.idioma = idioma;
            inValue.pais = pais;
            inValue.paginas = paginas;
            inValue.ImagenURL = ImagenURL;
            inValue.Descripcion = Descripcion;
            return ((Libreria.svcLibreria.IService1)(this)).NuevoLibroAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:49585/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_IService1,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.ServiceReference.Platforms", "11.0.0.0")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement() {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes {
            get {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema() {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer) {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            ) {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader) {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            ) {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element)) {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else {
                    reader.Skip();
                }
            }
        }
    }
}
