//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrosGrid.LibrosRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LibrosRef.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerListaLibros", ReplyAction="http://tempuri.org/IService1/ObtenerListaLibrosResponse")]
        System.Data.DataSet ObtenerListaLibros();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerListaLibros", ReplyAction="http://tempuri.org/IService1/ObtenerListaLibrosResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ObtenerListaLibrosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerListaGeneros", ReplyAction="http://tempuri.org/IService1/ObtenerListaGenerosResponse")]
        System.Data.DataSet ObtenerListaGeneros();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerListaGeneros", ReplyAction="http://tempuri.org/IService1/ObtenerListaGenerosResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ObtenerListaGenerosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerListaAutor", ReplyAction="http://tempuri.org/IService1/ObtenerListaAutorResponse")]
        System.Data.DataSet ObtenerListaAutor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerListaAutor", ReplyAction="http://tempuri.org/IService1/ObtenerListaAutorResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ObtenerListaAutorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerListaEditorial", ReplyAction="http://tempuri.org/IService1/ObtenerListaEditorialResponse")]
        System.Data.DataSet ObtenerListaEditorial();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerListaEditorial", ReplyAction="http://tempuri.org/IService1/ObtenerListaEditorialResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ObtenerListaEditorialAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerListaLibrosNombres", ReplyAction="http://tempuri.org/IService1/ObtenerListaLibrosNombresResponse")]
        System.Data.DataSet ObtenerListaLibrosNombres();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerListaLibrosNombres", ReplyAction="http://tempuri.org/IService1/ObtenerListaLibrosNombresResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ObtenerListaLibrosNombresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscaLibro", ReplyAction="http://tempuri.org/IService1/BuscaLibroResponse")]
        System.Data.DataSet BuscaLibro(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscaLibro", ReplyAction="http://tempuri.org/IService1/BuscaLibroResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> BuscaLibroAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscaGenero", ReplyAction="http://tempuri.org/IService1/BuscaGeneroResponse")]
        System.Data.DataSet BuscaGenero(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscaGenero", ReplyAction="http://tempuri.org/IService1/BuscaGeneroResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> BuscaGeneroAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscaAutor", ReplyAction="http://tempuri.org/IService1/BuscaAutorResponse")]
        System.Data.DataSet BuscaAutor(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscaAutor", ReplyAction="http://tempuri.org/IService1/BuscaAutorResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> BuscaAutorAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscaEditorial", ReplyAction="http://tempuri.org/IService1/BuscaEditorialResponse")]
        System.Data.DataSet BuscaEditorial(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscaEditorial", ReplyAction="http://tempuri.org/IService1/BuscaEditorialResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> BuscaEditorialAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerListaLibrosOrdenada", ReplyAction="http://tempuri.org/IService1/ObtenerListaLibrosOrdenadaResponse")]
        System.Data.DataSet ObtenerListaLibrosOrdenada(int quien, int orden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerListaLibrosOrdenada", ReplyAction="http://tempuri.org/IService1/ObtenerListaLibrosOrdenadaResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ObtenerListaLibrosOrdenadaAsync(int quien, int orden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NuevoGenero", ReplyAction="http://tempuri.org/IService1/NuevoGeneroResponse")]
        void NuevoGenero(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NuevoGenero", ReplyAction="http://tempuri.org/IService1/NuevoGeneroResponse")]
        System.Threading.Tasks.Task NuevoGeneroAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NuevoAutor", ReplyAction="http://tempuri.org/IService1/NuevoAutorResponse")]
        void NuevoAutor(string nombre, string APaterno, string Nacionalidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NuevoAutor", ReplyAction="http://tempuri.org/IService1/NuevoAutorResponse")]
        System.Threading.Tasks.Task NuevoAutorAsync(string nombre, string APaterno, string Nacionalidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NuevoEditorial", ReplyAction="http://tempuri.org/IService1/NuevoEditorialResponse")]
        void NuevoEditorial(string nombre, string Direccion, string Estado, string Pais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NuevoEditorial", ReplyAction="http://tempuri.org/IService1/NuevoEditorialResponse")]
        System.Threading.Tasks.Task NuevoEditorialAsync(string nombre, string Direccion, string Estado, string Pais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NuevoLibro", ReplyAction="http://tempuri.org/IService1/NuevoLibroResponse")]
        void NuevoLibro(string nombre, int autor, int editorial, int genero, string idioma, string pais, int paginas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NuevoLibro", ReplyAction="http://tempuri.org/IService1/NuevoLibroResponse")]
        System.Threading.Tasks.Task NuevoLibroAsync(string nombre, int autor, int editorial, int genero, string idioma, string pais, int paginas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditaGenero", ReplyAction="http://tempuri.org/IService1/EditaGeneroResponse")]
        void EditaGenero(int id, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditaGenero", ReplyAction="http://tempuri.org/IService1/EditaGeneroResponse")]
        System.Threading.Tasks.Task EditaGeneroAsync(int id, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditaAutor", ReplyAction="http://tempuri.org/IService1/EditaAutorResponse")]
        void EditaAutor(int id, string nombre, string APaterno, string Nacionalidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditaAutor", ReplyAction="http://tempuri.org/IService1/EditaAutorResponse")]
        System.Threading.Tasks.Task EditaAutorAsync(int id, string nombre, string APaterno, string Nacionalidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditaEditorial", ReplyAction="http://tempuri.org/IService1/EditaEditorialResponse")]
        void EditaEditorial(int id, string nombre, string Direccion, string Estado, string Pais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditaEditorial", ReplyAction="http://tempuri.org/IService1/EditaEditorialResponse")]
        System.Threading.Tasks.Task EditaEditorialAsync(int id, string nombre, string Direccion, string Estado, string Pais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditaLibro", ReplyAction="http://tempuri.org/IService1/EditaLibroResponse")]
        void EditaLibro(int id, string nombre, int autor, int editorial, int genero, string idioma, string pais, int paginas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditaLibro", ReplyAction="http://tempuri.org/IService1/EditaLibroResponse")]
        System.Threading.Tasks.Task EditaLibroAsync(int id, string nombre, int autor, int editorial, int genero, string idioma, string pais, int paginas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerDetalleLibro", ReplyAction="http://tempuri.org/IService1/ObtenerDetalleLibroResponse")]
        System.Data.DataSet ObtenerDetalleLibro(int libro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerDetalleLibro", ReplyAction="http://tempuri.org/IService1/ObtenerDetalleLibroResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ObtenerDetalleLibroAsync(int libro);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : LibrosGrid.LibrosRef.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<LibrosGrid.LibrosRef.IService1>, LibrosGrid.LibrosRef.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ObtenerListaLibros() {
            return base.Channel.ObtenerListaLibros();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ObtenerListaLibrosAsync() {
            return base.Channel.ObtenerListaLibrosAsync();
        }
        
        public System.Data.DataSet ObtenerListaGeneros() {
            return base.Channel.ObtenerListaGeneros();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ObtenerListaGenerosAsync() {
            return base.Channel.ObtenerListaGenerosAsync();
        }
        
        public System.Data.DataSet ObtenerListaAutor() {
            return base.Channel.ObtenerListaAutor();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ObtenerListaAutorAsync() {
            return base.Channel.ObtenerListaAutorAsync();
        }
        
        public System.Data.DataSet ObtenerListaEditorial() {
            return base.Channel.ObtenerListaEditorial();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ObtenerListaEditorialAsync() {
            return base.Channel.ObtenerListaEditorialAsync();
        }
        
        public System.Data.DataSet ObtenerListaLibrosNombres() {
            return base.Channel.ObtenerListaLibrosNombres();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ObtenerListaLibrosNombresAsync() {
            return base.Channel.ObtenerListaLibrosNombresAsync();
        }
        
        public System.Data.DataSet BuscaLibro(int id) {
            return base.Channel.BuscaLibro(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BuscaLibroAsync(int id) {
            return base.Channel.BuscaLibroAsync(id);
        }
        
        public System.Data.DataSet BuscaGenero(int id) {
            return base.Channel.BuscaGenero(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BuscaGeneroAsync(int id) {
            return base.Channel.BuscaGeneroAsync(id);
        }
        
        public System.Data.DataSet BuscaAutor(int id) {
            return base.Channel.BuscaAutor(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BuscaAutorAsync(int id) {
            return base.Channel.BuscaAutorAsync(id);
        }
        
        public System.Data.DataSet BuscaEditorial(int id) {
            return base.Channel.BuscaEditorial(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BuscaEditorialAsync(int id) {
            return base.Channel.BuscaEditorialAsync(id);
        }
        
        public System.Data.DataSet ObtenerListaLibrosOrdenada(int quien, int orden) {
            return base.Channel.ObtenerListaLibrosOrdenada(quien, orden);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ObtenerListaLibrosOrdenadaAsync(int quien, int orden) {
            return base.Channel.ObtenerListaLibrosOrdenadaAsync(quien, orden);
        }
        
        public void NuevoGenero(string nombre) {
            base.Channel.NuevoGenero(nombre);
        }
        
        public System.Threading.Tasks.Task NuevoGeneroAsync(string nombre) {
            return base.Channel.NuevoGeneroAsync(nombre);
        }
        
        public void NuevoAutor(string nombre, string APaterno, string Nacionalidad) {
            base.Channel.NuevoAutor(nombre, APaterno, Nacionalidad);
        }
        
        public System.Threading.Tasks.Task NuevoAutorAsync(string nombre, string APaterno, string Nacionalidad) {
            return base.Channel.NuevoAutorAsync(nombre, APaterno, Nacionalidad);
        }
        
        public void NuevoEditorial(string nombre, string Direccion, string Estado, string Pais) {
            base.Channel.NuevoEditorial(nombre, Direccion, Estado, Pais);
        }
        
        public System.Threading.Tasks.Task NuevoEditorialAsync(string nombre, string Direccion, string Estado, string Pais) {
            return base.Channel.NuevoEditorialAsync(nombre, Direccion, Estado, Pais);
        }
        
        public void NuevoLibro(string nombre, int autor, int editorial, int genero, string idioma, string pais, int paginas) {
            base.Channel.NuevoLibro(nombre, autor, editorial, genero, idioma, pais, paginas);
        }
        
        public System.Threading.Tasks.Task NuevoLibroAsync(string nombre, int autor, int editorial, int genero, string idioma, string pais, int paginas) {
            return base.Channel.NuevoLibroAsync(nombre, autor, editorial, genero, idioma, pais, paginas);
        }
        
        public void EditaGenero(int id, string nombre) {
            base.Channel.EditaGenero(id, nombre);
        }
        
        public System.Threading.Tasks.Task EditaGeneroAsync(int id, string nombre) {
            return base.Channel.EditaGeneroAsync(id, nombre);
        }
        
        public void EditaAutor(int id, string nombre, string APaterno, string Nacionalidad) {
            base.Channel.EditaAutor(id, nombre, APaterno, Nacionalidad);
        }
        
        public System.Threading.Tasks.Task EditaAutorAsync(int id, string nombre, string APaterno, string Nacionalidad) {
            return base.Channel.EditaAutorAsync(id, nombre, APaterno, Nacionalidad);
        }
        
        public void EditaEditorial(int id, string nombre, string Direccion, string Estado, string Pais) {
            base.Channel.EditaEditorial(id, nombre, Direccion, Estado, Pais);
        }
        
        public System.Threading.Tasks.Task EditaEditorialAsync(int id, string nombre, string Direccion, string Estado, string Pais) {
            return base.Channel.EditaEditorialAsync(id, nombre, Direccion, Estado, Pais);
        }
        
        public void EditaLibro(int id, string nombre, int autor, int editorial, int genero, string idioma, string pais, int paginas) {
            base.Channel.EditaLibro(id, nombre, autor, editorial, genero, idioma, pais, paginas);
        }
        
        public System.Threading.Tasks.Task EditaLibroAsync(int id, string nombre, int autor, int editorial, int genero, string idioma, string pais, int paginas) {
            return base.Channel.EditaLibroAsync(id, nombre, autor, editorial, genero, idioma, pais, paginas);
        }
        
        public System.Data.DataSet ObtenerDetalleLibro(int libro) {
            return base.Channel.ObtenerDetalleLibro(libro);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ObtenerDetalleLibroAsync(int libro) {
            return base.Channel.ObtenerDetalleLibroAsync(libro);
        }
    }
}
